# -*- mode: ruby -*-
# vi: set ft=ruby :

os = ENV.fetch("WP_OS", "ubuntu")

BOXES = {
  "ubuntu" => "bento/ubuntu-24.04",
  "centos" => "generic/centos9s"
}

box = BOXES.fetch(os) { abort "Неизвестный WP_OS=#{os}, допустимо: #{BOXES.keys.join(', ')}" }

Vagrant.configure(2) do |config|
        config.vm.box = box
        config.vm.box_check_update = false
        config.vm.provider "virtualbox" do |vb|
                vb.memory = 1536
                vb.cpus   = 1
	end
	config.vm.define "wordpress" do |wordpress|
    wordpress.vm.hostname = "wordpress"
    wordpress.vm.network "private_network", ip: "192.168.56.10"
  end
end
