{{- if .Values.wordpress.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.wordpress.name }}
  namespace: {{ include "wordpress-app.namespace" . }}
  labels:
    app: {{ .Values.wordpress.label }}
  {{- with .Values.wordpress.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.wordpress.ingress.className }}
  ingressClassName: {{ .Values.wordpress.ingress.className }}
  {{- end }}
  {{- if .Values.wordpress.ingress.tls }}
  tls:
    {{- toYaml .Values.wordpress.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.wordpress.ingress.host }}
      http:
        paths:
          - path: {{ .Values.wordpress.ingress.path }}
            pathType: {{ .Values.wordpress.ingress.pathType }}
            backend:
              service:
                name: {{ .Values.wordpress.name }}
                port:
                  number: {{ .Values.wordpress.service.port }}
{{- end }}
