apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wordpress.name }}
  namespace: {{ include "wordpress-app.namespace" . }}
  labels:
    app: {{ .Values.wordpress.label }}
spec:
  type: {{ .Values.wordpress.service.type }}
  selector:
    app: {{ .Values.wordpress.label }}
  ports:
    - port: {{ .Values.wordpress.service.port }}
      targetPort: 80
      {{- if and (eq .Values.wordpress.service.type "NodePort") .Values.wordpress.service.nodePort }}
      nodePort: {{ .Values.wordpress.service.nodePort }}
      {{- end }}
