# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
        config.vm.box = "bento/ubuntu-24.04"
        config.vm.box_check_update = false
        config.vm.provider "virtualbox" do |vb|
                vb.memory = 1536
                vb.cpus   = 1
        end
    config.vm.define "dev" do |dev|
    dev.vm.hostname = "dev"
    dev.vm.network "private_network", ip: "192.168.56.11"
  end
	config.vm.define "prod" do |prod|
    prod.vm.hostname = "prod"
    prod.vm.network "private_network", ip: "192.168.56.10"
  end
end
