apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress-app.fullname" . }}-secret
  namespace: {{ include "wordpress-app.namespace" . }}
  labels:
    {{- include "wordpress-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.auth.rootPassword | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.auth.password | quote }}
  WORDPRESS_DB_PASSWORD: {{ .Values.mysql.auth.password | quote }}
