apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.serviceName }}
  namespace: {{ include "wordpress-app.namespace" . }}
  labels:
    app: {{ .Values.mysql.label }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.mysql.label }}
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.port }}
