global:
  scrape_interval: '5s'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - localhost:9090

  - job_name: cadvisor
    static_configs:
      - targets:
        - cadvisor:8080

  - job_name: blackbox
    static_configs:
      - targets:
        - blackbox:9115
  
  - job_name: blackbox-http
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://ui:9292/
          - http://ui:9292/new
          - http://post:5000/healthcheck
          - http://comment:9292/healthcheck
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: ui
    metrics_path: /metrics
    static_configs:
      - targets: 
        - ui:9292