---
mysql_packages:
  - mariadb-server
  - mariadb
  - python3-PyMySQL

mysql_service_name: mariadb
mysql_config_file: /etc/my.cnf.d/server.cnf
mysql_config_dir: /etc/my.cnf.d
mysql_socket: /var/lib/mysql/mysql.sock
