# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
        config.vm.box = "bento/ubuntu-24.04"
        config.vm.box_check_update = false
        config.vm.provider "virtualbox" do |vb|
                vb.memory = 1536
                vb.cpus   = 1
        end
        config.vm.define "store" do |store|
    store.vm.hostname = "store"
    store.vm.network "private_network", ip: "192.168.56.11"
    store.vm.provision "shell", path: "store.sh"
  end
	config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.56.10"
    server.vm.provision "shell", path: "server.sh"
  end
end
